// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trrjtwvjquzxllmdtxmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRycmp0d3ZqcXV6eGxsbWR0eG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjgxMzksImV4cCI6MjA2ODI0NDEzOX0.ZI2ryUZjeRzZhc54bBqUke6fMljDrj6CpjesaQvhFBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});